name = "loomsandbunkars"
compatibility_date = "2025-07-26"

[assets]
directory = "./public/"
not_found_handling = "single-page-application"

[observability.logs]
enabled = true

[env.production.send_email]
CONTACT_EMAIL = { destination_address = "shubxam@gmail.com" }

[env.preview.send_email]
CONTACT_EMAIL = { destination_address = "shubxam@gmail.com" }