name = "loomsandbunkars"
main = "src/index.js"
compatibility_date = "2025-07-26"

[assets]
directory = "./public/"
binding = "ASSETS"

[observability.logs]
enabled = true

[[send_email]]
name = "CONTACT_EMAIL"
destination_address = "shubxam@gmail.com"